apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: node-js
        image: arpittest1996/aws-bootcamp:node-js-v3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000 


---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: node-js
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP